### ISSUE TITLE
Deployment 2020-2.0 checklist

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II-FXI/profile_collection#4]
## Previsit 
- [x] Make sure that the current latest environments are pushed to all the bl machines
- [x] Skim the IPython startup files in `profile_collection`
  - Check if it's safe to start `bsui` remotely (does it touch any hardware?) - use `git grep .put` or `git grep caput`
- [x] Check for outstanding PRs and issues on beamline repos
- [x] Check if beamline specific packages pushed to the BL machines
- [x] (Optional) Enable CI

## Housekeeping 
- [x] Add BL staff to the BL GitHub organization as owners
- [x] Work with BL staff to commit any un-committed changes to their profiles
- [x] Tag the profile as-found as 2019C3.x
- [x] Discuss with BL staff which conda envs they want to keep/delete and perform the cleanup
- [x] Check/update the beamline's inventory with the BL staff (in https://github.com/NSLS-II/playbooks/blob/master/production)

## Test deployment 
- [x] In `~/.bashrc` add the following and remember to `source ~/.bashrc` afterward.
  ```
  BLUESKY_LOG_FILE=/var/log/bluesky.log
  BLUESKY_IPYTHON_LOG_FILE=/var/log/bluesky_ipython.log
  ```
  and (if needed) create those directories, making them world-read/write-able.
- [x] Append to `00-startup.py`  https://gist.github.com/jklynch/a4366b8900ec0c03883403455ae711b2
- [x] Run profile against new environment
  - `BS_ENV=collection-2020-2.0rc7 bsui`
- [x] Update the profile as needed to run:
  - [x] Replace `.value` -> `.get()` if it's in a `Device`, or with `yield from bps.read()` if in a plan
  - [x] `history.sqlite` issue - see https://blueskyproject.io/bluesky/metadata.html#persistence-between-sessions
  - [x] potential issue with images in databroker V2
- [x] Run acceptance tests (if any) and run a representative set of scans for the beamline
- [x] Tag the updated profile as `2020C2.0`
- [x] Update BSUI via ansible to use the new environment (http://nsls-ii.github.io/deployment/upgrading-beamlines.html#change-bsui-s-default-environment)

**Comment by cryos** [comment]
There are several occurrences of .put and a few caput commands in the startup files
 * .put in `10-area-detector.py`, `13-pzt.py`, `40-scans.py`, `41-scans_pzt.py`, `42-scans_other.py` and `98-user_scan.py`
 * caput in `41-scans_pzt.py`

**Comment by tacaswell** [comment]
- The `.put` s in 10-area-detector.py are of the allowed category (in ophyd methods)
- The `.put`s in 10-pzt.py are of a "not worth fighting about" category because they are setting some configuration on the IOC that should be set at the IOC level.  They can probably be removed, but if they configuration has not been fixed then if the server restarts we will get back to the broken configuration (the issue is that IOCs can report the "precision" of their float values and were reporting "0" which means "no decimal places" which means that in the table scanning from 0.1 to 0.5 just shows up as "0" which is less than strictly helpful). 
 - the `.put` in 40-scans.py should be changed to use `bsp.mv` instead.

**Comment by cryos** [comment]
I changed 40-scans.py and 42-scans_other.py. 98-user_scan.py was open, only had one occurrence.

**Comment by danielballan** [comment]
Success! We opened issues for things that we need to follow up on in future deployments.
